name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build:
    # temporarily pin macOS 27 until latest catches up with swift 6.4 required by package
    runs-on: xcode-27
    environment: default
    steps:
      - uses: actions/checkout@v7
      - name: Resolve frameworks
        run: swift package resolve
